version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=todolist
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3308:3306'
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mysql
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src

volumes:
  mysql_data: